# Generated by Django 3.0.1 on 2020-01-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('pontos_turisticos', '0004_pontosturisticos_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Localizacao'),
            preserve_default=False,
        ),
    ]
