# Generated by Django 3.0.1 on 2020-01-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('pontos_turisticos', '0005_pontosturisticos_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Localizacao'),
        ),
    ]
