# Generated by Django 3.0.1 on 2020-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0006_auto_20200111_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
